services:
  nats:
    image: nats:2.10-alpine
    container_name: nats-server
    ports:
      - "4222:4222"   # Client connections
      - "8222:8222"   # HTTP monitoring
      - "6222:6222"   # Clustering
    command: 
      - "-p"
      - "4222"
      - "-m"
      - "8222"
      - "-js"         # Enable JetStream
      - "-D"          # Debug mode
    volumes:
      - nats-data:/data
    restart: unless-stopped

  # NATS management UI (optional, for development convenience)
  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    depends_on:
      - nats
    entrypoint: /bin/sh
    stdin_open: true
    tty: true

volumes:
  nats-data:
