name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        version: 0.14.0

    - name: Run unit tests
      run: zig build test-unit

    - name: Run integration tests
      run: zig build test-e2e
